### ISSUE TITLE
cfa IP使用问题

### ISSUE THREAD

**Issue by maobohuan** [sipeed/TangMega-138KPro-example#7]
为什么我在138k pro板子上使用cfa IP将raw格式数据rggb转为rbg数据并没有正确输出呢？

**Comment by kyonmiriam** [comment]
Sorry, since your question lacks details and is beyond the scope of this repository, this issue will be closed.

**Comment by kyonmiriam** [comment]
If you encounter problems when using the IP included in GOWIN IDE, you should first contact GOWIN for technical support.

**Comment by kyonmiriam** [comment]
If you encounter problems when using the IP included in GOWIN IDE, you should first contact GOWIN for technical support.
